# PostgreSQL
spring.datasource.url=jdbc:postgresql://d8j272647okc739r01vg-a.ohio-postgres.render.com/logistica_ek37
spring.datasource.username=anacc
spring.datasource.password=wdfgaLAQB1F1P5GRH74oAuSIKK47qEN7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Opcional
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Server
server.port=${PORT:8080}

# Metrics
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.apiKey=${DD_API_KEY}
management.datadog.metrics.export.step=30s
