# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d9kdo05g1s2s73ftodu0-a.oregon-postgres.render.com/logistica_nfs2
spring.datasource.username=anacc
spring.datasource.password=YmHKLa870tLP1MiNKn7lMDq00IRusILY
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Opcional
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.cloud.openfeign.okhttp.enabled=true

# Server
server.port=${PORT:8080}

# Metrics
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.apiKey=${DD_API_KEY}
management.datadog.metrics.export.step=30s
